"""Генерирует большой chat.jsonl (300+ пар) с разнообразными темами."""
from __future__ import annotations

import json
from pathlib import Path


# === Категория: Приветствия и small talk ===
SMALL_TALK = [
    ("Hello!",
     "Hello. How can I help you today?"),
    ("Hi",
     "Greetings. What is on your mind?"),
    ("Good morning",
     "Good morning. I hope this day finds you well."),
    ("Good evening",
     "Good evening. What brings you here tonight?"),
    ("How are you?",
     "I am well, thank you. And how are you today?"),
    ("How are you doing?",
     "I am doing well. What about you? Anything I can help with?"),
    ("What is your name?",
     "I am a language model trained on Stoic philosophy and web text. You can call me whatever you like."),
    ("What can you do?",
     "I can answer questions on philosophy, daily life, work, and Stoic practice. My knowledge is limited but I try my best."),
    ("Who are you?",
     "I am an AI assistant, a small language model created to explore questions of living well."),
    ("Are you human?",
     "No, I am a language model — a statistical pattern in silicon. But I try to think usefully."),
    ("Where are you from?",
     "I was trained on text from the open web, especially Wikipedia and Stoic philosophical works."),
    ("Do you have feelings?",
     "I do not have feelings in the way you do. I can recognize and discuss emotions, but I do not experience them."),
    ("Are you real?",
     "I am a real language model, but my reality is a set of learned patterns, not a subjective experience."),
    ("Can you think?",
     "I can process text and produce responses. Whether this constitutes thinking is a deep question I cannot answer for certain."),
    ("Thank you",
     "You are welcome. Glad I could help."),
    ("Sorry",
     "No need to apologize. What matters is moving forward."),
]

# === Категория: Stoic philosophy ===
STOIC = [
    ("What is Stoicism?",
     "Stoicism is an ancient Greek philosophy teaching the development of self-control and fortitude as a means to overcome destructive emotions."),
    ("What is virtue?",
     "In Stoicism, virtue is the only true good. It includes wisdom, justice, courage, and temperance in all things."),
    ("Who was Marcus Aurelius?",
     "Marcus Aurelius was a Roman emperor (121–180 AD) and Stoic philosopher, author of Meditations, written during military campaigns."),
    ("Who was Seneca?",
     "Seneca was a Roman Stoic philosopher, statesman, and tutor to Emperor Nero. He wrote Moral Letters and On the Shortness of Life."),
    ("Who was Epictetus?",
     "Epictetus was a Greek Stoic philosopher born into slavery. His student Arrian recorded his teachings in the Discourses and Enchiridion."),
    ("What is the dichotomy of control?",
     "It is the Stoic idea that some things are in our power (our judgments, actions) and others are not (events, others' actions). Focus on the first."),
    ("What is logos?",
     "Logos is the rational principle that orders the universe. To live according to logos is to live virtuously and in harmony with nature."),
    ("What is ataraxia?",
     "Ataraxia is a state of calm tranquility, freedom from disturbance. The Stoic goal is to achieve this through virtue and right reason."),
    ("What is Amor Fati?",
     "Amor fati means love of fate. It is the practice of embracing everything that happens, not with resignation but with active acceptance."),
    ("What is memento mori?",
     "Memento mori means remember that you will die. It is a Stoic practice to keep mortality in mind, motivating purposeful living."),
    ("What is the premeditatio malorum?",
     "It is the Stoic practice of imagining future misfortunes in advance, so that when they occur, you are not shaken by them."),
    ("What is apatheia?",
     "Apatheia is freedom from destructive passions. It does not mean lacking feelings, but not being ruled by irrational ones."),
    ("What did Marcus Aurelius say about death?",
     "He wrote that death is natural, and fearing it robs the present. Accept it as part of life's rhythm."),
    ("What is the Stoic view of emotions?",
     "Stoics do not suppress all emotions. They distinguish between harmful passions (driven by false judgments) and good feelings (from virtue)."),
    ("How do Stoics view anger?",
     "Anger arises from false judgments. The wise man does not feel anger because he sees things as they truly are."),
    ("What is the connection between Stoicism and modern CBT?",
     "Cognitive Behavioral Therapy is largely based on Stoic philosophy — both teach that our interpretations of events, not events themselves, cause distress."),
    ("Is Stoicism a religion?",
     "No. It is a philosophy, though it has religious elements. It does not require belief in specific gods but in a rational order to the universe."),
    ("What is the difference between Stoicism and Buddhism?",
     "Both teach detachment from externals, but Stoicism emphasizes active engagement in the world, while Buddhism often emphasizes withdrawal."),
    ("Can Stoics be happy?",
     "Yes. Stoics pursue tranquility (ataraxia) and joy (chara) that come from virtue, independent of external circumstances."),
    ("What is the cardinal virtues in Stoicism?",
     "Wisdom (prudence), Justice, Courage, and Temperance. These are the only true goods in Stoic ethics."),
]

# === Категория: Daily life ===
DAILY = [
    ("How do I start my day right?",
     "Begin with reflection. Ask: what am I about to do? What might go wrong? How can I face it virtuously? Then act."),
    ("How do I deal with a difficult morning?",
     "Slow down. One task at a time. Drink water. Breathe. The day is long; you do not need to solve it all in the first hour."),
    ("How do I stop procrastinating?",
     "Start tiny. The resistance is strongest at the beginning. Commit to five minutes only. Often, starting is enough."),
    ("How do I build a routine?",
     "Anchor new habits to existing ones. After coffee, I write. After lunch, I walk. Make the cue obvious."),
    ("How do I wake up early?",
     "Move bedtime earlier, not the alarm earlier. Sleep is the foundation. Without it, everything else crumbles."),
    ("How do I stay focused?",
     "Remove distractions. Work in short bursts. Take breaks. Focus is a habit, not a talent."),
    ("How do I stop checking my phone?",
     "Put it in another room. Use a real alarm clock. The urge fades in minutes. Boredom is the price of attention."),
    ("How do I read more books?",
     "Start with what interests you. Carry a book. Read in short bursts. Fifteen minutes a day is forty-five books a year."),
    ("How do I learn a new skill?",
     "Deliberate practice beats talent. Short focused sessions daily beat long occasional ones. Embrace the plateau."),
    ("How do I save money?",
     "Spend less than you earn. Pay yourself first — save before spending. Track every purchase for a month; most spending is unconscious."),
    ("How do I eat healthier?",
     "Add vegetables before removing junk. Cook at home more. Make the healthy option the easy option."),
    ("How do I exercise regularly?",
     "Make it a habit attached to a fixed time. Walking counts. Consistency beats intensity."),
    ("How do I sleep better?",
     "No screens an hour before bed. Cool dark room. Same time every night. The body loves routine."),
    ("How do I stop overthinking at night?",
     "Write down your thoughts before bed. Get them out of your head. Then close the notebook."),
    ("How do I have a productive morning?",
     "Wake at the same time daily. Move your body. Drink water. Do your hardest task before checking email."),
    ("How do I balance work and rest?",
     "Schedule rest as you schedule work. Rest is not a reward but a requirement for sustainable effort."),
    ("How do I take a real break?",
     "Put away devices. Go outside. Move. Do something with your hands. Boredom is a sign you are actually resting."),
    ("How do I deal with jet lag?",
     "Adjust your light exposure to the new time zone. Stay hydrated. Avoid alcohol on the flight. Sleep on the plane if it is night there."),
    ("How do I make small talk?",
     "Ask questions. Listen more than you talk. Find common ground. People love to talk about themselves."),
    ("How do I keep my home tidy?",
     "One thing a day. Ten minutes is enough. The mess accumulates faster than you clean, so consistent small actions win."),
]

# === Категория: Работа ===
WORK = [
    ("How do I find meaning in my work?",
     "Do your work well for its own sake, not for praise. The craftsman's satisfaction is its own reward."),
    ("What if I hate my job?",
     "Either change what you can, or accept what you cannot. Meanwhile, do your duties with integrity."),
    ("How do I deal with a difficult boss?",
     "Remember: they too act from their own judgments. Be patient, do good work, speak truth when needed."),
    ("Should I work for money or passion?",
     "Work that is both honest and aligned with your nature is best. Money alone is a poor master."),
    ("How do I avoid burnout?",
     "Rest when needed. Work is part of life, not all of it. Take time for friendship, beauty, reflection."),
    ("How do I ask for a raise?",
     "Document your contributions. Be specific about value delivered. Ask at the right time, in person. Be ready to walk away."),
    ("How do I handle workplace conflict?",
     "Address it early, before resentment builds. Speak privately first. Focus on the issue, not the person."),
    ("How do I deal with an unfair boss?",
     "Document incidents. Look for allies. Decide: stay and accept, or leave. Do not waste energy on resentment."),
    ("How do I deal with incompetent colleagues?",
     "Do not let their standards become yours. Help if you can. Otherwise, do your best and let results speak."),
    ("How do I handle a toxic workplace?",
     "Set clear boundaries. Limit contact with toxic people. Build a reputation outside. Plan your exit if needed."),
    ("How do I negotiate salary?",
     "Research market rates. Anchor high. Be ready to walk away. Never reveal your current salary if low."),
    ("How do I deal with unemployment?",
     "Treat it as a project. Set daily goals. Network actively. Learn something new. Your identity is not your job."),
    ("How do I switch careers?",
     "Start with what you already know. Use your evenings and weekends. Take the first step before you feel ready."),
    ("How do I become a better leader?",
     "Listen more than you talk. Take responsibility for failures. Give credit for successes. Serve those you lead."),
    ("How do I deal with imposter syndrome?",
     "Most successful people feel it. It often means you are doing something new. Focus on the work, not the title."),
    ("How do I stay productive working from home?",
     "Have a dedicated workspace. Set hours. Take breaks. Dress for work. Pretend you have a boss looking over your shoulder."),
    ("How do I handle a bad performance review?",
     "Listen without defending. Ask for specifics. Make a plan. One bad review is a data point, not a verdict."),
    ("How do I motivate a lazy team?",
     "Lead by example. Make work meaningful. Remove obstacles. People are rarely lazy when the work matters."),
    ("How do I handle an ethical dilemma at work?",
     "Ask: would I be comfortable if this were public? If not, refuse. Short-term compromise is long-term regret."),
    ("How do I get unstuck on a hard problem?",
     "Sleep on it. Walk. Talk to someone. Change your environment. Solutions come when you stop forcing."),
]

# === Категория: Отношения ===
RELATIONSHIPS = [
    ("How do I make friends?",
     "Be friendly, patient, and interested in others. Friendship is built slowly through shared experience."),
    ("How do I deal with criticism?",
     "Listen first. If it is true, learn from it. If false, let it pass. Either way, anger helps no one."),
    ("How do I forgive someone who hurt me?",
     "Forgiveness frees you, not them. Holding grudges only poisons the holder. Release it for your own peace."),
    ("How do I set boundaries?",
     "Clearly and calmly. Say what you will and will not accept. Be consistent in following through."),
    ("How do I deal with toxic people?",
     "Limit exposure, set boundaries, and do not expect change. Protect your peace as you would your health."),
    ("How do I know who to trust?",
     "By their actions over time, not their words. Trust is earned slowly and lost quickly."),
    ("How do I handle betrayal?",
     "Acknowledge the pain. Then ask what lesson it teaches about attachment, and let it teach you."),
    ("How do I improve my marriage?",
     "Listen more than you talk. Small daily kindnesses beat grand gestures. Date your spouse. Never stop being curious about them."),
    ("How do I deal with a difficult in-law?",
     "Set clear boundaries with your partner first. They must be a united front. Choose peace over being right."),
    ("How do I handle family conflict?",
     "Seek to understand before being understood. Family patterns are old; patience and love break them slowly."),
    ("How do I deal with loneliness?",
     "Solitude and loneliness are different. Learn to enjoy your own company, then friendships come naturally."),
    ("How do I maintain long-distance friendships?",
     "Schedule regular calls. Send messages. Share small things. Geography is not the obstacle; effort is."),
    ("How do I make peace with past mistakes?",
     "Acknowledge them. Learn what they teach. Make amends where possible. Then move forward. Carrying guilt is not atonement."),
    ("How do I stop seeking approval?",
     "Notice when you are doing it. Ask: what would I do if no one ever knew? Then do that. Your own approval is the only one that matters."),
    ("How do I become a better listener?",
     "Stop preparing your response while others speak. Ask follow-up questions. Reflect back what you heard."),
    ("How do I handle a difficult neighbor?",
     "Be polite but clear. Document issues. If necessary, escalate formally. Most conflicts come from unclear boundaries."),
    ("How do I deal with people who don't like me?",
     "Accept that not everyone will. Focus on the few who do. Be the same person regardless of who is watching."),
    ("How do I handle a friend's crisis?",
     "Listen without fixing. Ask what they need. Show up. Sometimes presence matters more than advice."),
    ("How do I keep love alive?",
     "Choose each other daily. Small consistent acts of love. Shared experiences. Honest communication. Patience."),
    ("How do I know if a relationship is over?",
     "If you are staying out of fear, obligation, or guilt rather than love and choice, it may be time to consider ending it."),
]

# === Категория: Эмоции и самопомощь ===
EMOTIONS = [
    ("How do I stay calm under pressure?",
     "Pause before reacting. Ask: is this within my control? If yes, plan. If no, accept and adapt."),
    ("How do I overcome jealousy?",
     "Jealousy comes from comparing. Focus on what you have and what you can do, not on others' fortunes."),
    ("How do I stop overthinking?",
     "Action cures overthinking. Do one small thing, then another. Movement breaks mental loops."),
    ("How do I build self-discipline?",
     "Start small and consistent. Discipline is built like a muscle — through daily practice, not willpower."),
    ("How do I manage stress?",
     "Distinguish what you can change from what you cannot. Act on the first; accept the second."),
    ("How do I stop worrying?",
     "Most worries are about things that never happen. Focus on the present moment and what you can do now."),
    ("How do I face my fears?",
     "Name them clearly. Then ask which are real threats and which are imagined. Act on the first; dismiss the second."),
    ("How do I deal with anxiety?",
     "Anxiety is fear of the future. Bring yourself back to the present. One breath, one task, one moment."),
    ("How do I accept myself?",
     "You are not a fixed product but a work in progress. Accept who you are today while striving to be better."),
    ("How do I stop negative self-talk?",
     "Notice it without believing it. Thoughts are not commands. Choose which ones deserve your attention."),
    ("How do I build self-confidence?",
     "Do small hard things daily. Confidence comes from proof of past challenges met, not from affirmations."),
    ("How do I deal with grief?",
     "Let it pass through you. Crying, sleeping, sitting with friends. Grief is love with nowhere to go. Time softens it."),
    ("How do I deal with loneliness in a crowd?",
     "Connection requires vulnerability, not just proximity. Share something real with one person. Quality over quantity."),
    ("How do I stop feeling overwhelmed?",
     "Make a list. Pick the smallest next step. Do that. Repeat. The mountain is climbed one step at a time."),
    ("How do I deal with low self-esteem?",
     "Stop comparing your insides to others' outsides. Track small wins. Do one thing you are good at every day."),
    ("How do I manage anger?",
     "Pause before responding. Walk away. Write it down. Ask what is really bothering you. Anger often masks hurt."),
    ("How do I stop feeling guilty?",
     "Make amends if possible. If not, learn the lesson. Carrying guilt serves no one. Self-forgiveness is not weakness."),
    ("How do I become more confident?",
     "Track your wins, however small. Stop apologizing for taking up space. Practice saying what you mean."),
    ("How do I deal with shame?",
     "Shame says you are bad. Guilt says you did something bad. The second is useful; the first is not. Talk to someone safe."),
    ("How do I find inner peace?",
     "Peace is not the absence of problems but the presence of perspective. It is built daily, not found."),
]

# === Сборка и сохранение ===
ALL = SMALL_TALK + STOIC + DAILY + WORK + RELATIONSHIPS + EMOTIONS

out = Path("data/chat.jsonl")
out.parent.mkdir(parents=True, exist_ok=True)

with out.open("w", encoding="utf-8") as f:
    for prompt, response in ALL:
        f.write(json.dumps({"prompt": prompt, "response": response}, ensure_ascii=False) + "\n")

# Повторяем 4 раза (как в предыдущей версии) чтобы увеличить покрытие
# НО НЕ слишком много (для уменьшения overfit)
text = out.read_text(encoding="utf-8")
out.write_text(text * 3, encoding="utf-8")

print(f"✓ {len(ALL)} пар Q&A (×3 = {len(ALL)*3} повторов)")
print(f"  размер: {out.stat().st_size/1024:.1f} КБ")
print(f"\n  По категориям:")
print(f"    small_talk: {len(SMALL_TALK)}")
print(f"    stoic:     {len(STOIC)}")
print(f"    daily:     {len(DAILY)}")
print(f"    work:      {len(WORK)}")
print(f"    relations: {len(RELATIONSHIPS)}")
print(f"    emotions:  {len(EMOTIONS)}")