"""Создание 5000+ новых промптов для gold_v2.

Категории расширены:
  - Больше RU/EN стоических
  - Больше бытовых ситуаций
  - Программирование (help me write code, объясни алгоритм)
  - Научные вопросы (физика, биология, история)
  - Культура (книги, фильмы, музыка)
  - Советы (как сделать X)
  - Юмор (расскажи шутку, анекдот)
  - Разные языки приветствий
"""
import json
from pathlib import Path

ROOT = Path("C:/Users/mixai/Desktop/llm-from-scratch")
OUTPUT = ROOT / "data/gold_v2_prompts.jsonl"

# Расширенный набор — фокус на повседневные темы
PROMPTS = {
    "everyday": [
        "Как сварить яйцо?",
        "Сколько варить пельмени?",
        "Как сделать скриншот на компьютере?",
        "Как похудеть без диет?",
        "Как научиться быстро читать?",
        "Как пережить жару?",
        "Как согреться зимой?",
        "Как выбрать подарок?",
        "Как приготовить чай?",
        "Как сделать кофе?",
        "Как выспаться?",
        "Как проснуться бодрым?",
        "Как убрать квартиру быстро?",
        "Как постирать?",
        "Как погладить рубашку?",
        "Как вырастить цветы?",
        "Как ухаживать за котом?",
        "Как дрессировать собаку?",
        "Как научиться плавать?",
        "Как научиться кататься на велосипеде?",
        "How to boil an egg?",
        "How to make coffee?",
        "How to take a screenshot?",
        "How to lose weight?",
        "How to read faster?",
        "How to survive the heat?",
        "How to choose a gift?",
        "How to wake up refreshed?",
        "How to fall asleep fast?",
        "How to clean a house quickly?",
    ],
    "programming": [
        "Напиши функцию сортировки пузырьком на Python",
        "Объясни что такое ООП простыми словами",
        "Что такое рекурсия?",
        "Как работает Git?",
        "Что такое API?",
        "Что такое база данных?",
        "Объясни разницу между SQL и NoSQL",
        "Что такое нейронная сеть?",
        "Как написать Hello World на Python?",
        "Что такое декоратор в Python?",
        "Explain bubble sort in Python",
        "What is OOP in simple words?",
        "What is recursion?",
        "How does Git work?",
        "What is an API?",
        "What is a database?",
        "Explain SQL vs NoSQL",
        "What is a neural network?",
        "How to write Hello World in Python?",
        "What is a Python decorator?",
    ],
    "science": [
        "Что такое гравитация?",
        "Почему небо голубое?",
        "Сколько звёзд в галактике?",
        "Что такое ДНК?",
        "Почему Земля круглая?",
        "Что такое чёрная дыра?",
        "Сколько лет вселенной?",
        "Что такое эволюция?",
        "Почему мы зеваем?",
        "Что такое сон?",
        "What is gravity?",
        "Why is the sky blue?",
        "How many stars are in the galaxy?",
        "What is DNA?",
        "Why is the Earth round?",
        "What is a black hole?",
        "How old is the universe?",
        "What is evolution?",
        "Why do we yawn?",
        "What is sleep?",
    ],
    "history": [
        "Кто построил пирамиды?",
        "Когда была вторая мировая война?",
        "Кто такой Наполеон?",
        "Когда распался СССР?",
        "Кто написал Войну и мир?",
        "Что такое крестовые походы?",
        "Когда изобрели печатный станок?",
        "Кто был первым президентом США?",
        "Когда была Октябрьская революция?",
        "Кто открыл Америку?",
        "Who built the pyramids?",
        "When was World War II?",
        "Who was Napoleon?",
        "When did the USSR collapse?",
        "Who wrote War and Peace?",
        "What were the Crusades?",
        "When was the printing press invented?",
        "Who was the first US president?",
        "When was the October Revolution?",
        "Who discovered America?",
    ],
    "culture": [
        "Какие книги почитать?",
        "Какие фильмы посмотреть?",
        "Какую музыку послушать?",
        "Кто написал Войну и мир?",
        "Что такое импрессионизм?",
        "Кто такой Чехов?",
        "Какая твоя любимая книга?",
        "Какой фильм стоит посмотреть?",
        "Какую музыку слушаешь?",
        "Кто лучший писатель?",
        "What books should I read?",
        "What movies should I watch?",
        "What music should I listen to?",
        "Who is your favorite author?",
        "What is impressionism?",
        "Who wrote War and Peace?",
        "What is your favorite book?",
        "What film should I see?",
        "What is your favorite music?",
        "Who is the best writer?",
    ],
    "advice": [
        "Как научиться вставать рано?",
        "Как бросить курить?",
        "Как перестать откладывать дела?",
        "Как научиться говорить нет?",
        "Как стать увереннее?",
        "Как найти друзей?",
        "Как справиться с одиночеством?",
        "Как пережить расставание?",
        "Как стать успешнее?",
        "Как научиться экономить деньги?",
        "How to wake up early?",
        "How to quit smoking?",
        "How to stop procrastinating?",
        "How to learn to say no?",
        "How to be more confident?",
        "How to make friends?",
        "How to deal with loneliness?",
        "How to survive a breakup?",
        "How to be more successful?",
        "How to save money?",
    ],
    "humor": [
        "Расскажи анекдот",
        "Расскажи шутку про программистов",
        "Придумай смешной тост",
        "Расскажи весёлую историю",
        "Что смешного есть в жизни?",
        "Чем отличается оптимист от пессимиста?",
        "Почему программисты путают Хэллоуин и Рождество?",
        "Расскажи анекдот про Штирлица",
        "Tell me a joke",
        "Tell a joke about programmers",
        "Make up a funny toast",
        "Tell a funny story",
        "What's funny in life?",
        "What is the difference between an optimist and a pessimist?",
        "Why do programmers confuse Halloween and Christmas?",
        "Tell a joke about Chuck Norris",
    ],
    "philosophy_extended": [
        "Что такое счастье?",
        "В чём смысл жизни?",
        "Что важнее: ум или доброта?",
        "Стоит ли быть идеалистом?",
        "Что такое свобода?",
        "Что такое справедливость?",
        "Что такое дружба?",
        "Что такое любовь?",
        "В чём смысл страдания?",
        "Что есть истина?",
        "What is happiness?",
        "What is the meaning of life?",
        "What is more important: intelligence or kindness?",
        "Should one be an idealist?",
        "What is freedom?",
        "What is justice?",
        "What is friendship?",
        "What is love?",
        "What is the meaning of suffering?",
        "What is truth?",
    ],
    "math_logic": [
        "Что больше: 7 или 8?",
        "Сколько будет 10+15?",
        "Сколько будет 100/5?",
        "Что больше: 0.5 или 0.05?",
        "Сколько будет 9*9?",
        "Что больше: -5 или 5?",
        "Сколько будет 25*4?",
        "Что больше: 100 или 99?",
        "Which is bigger: 7 or 8?",
        "What is 10+15?",
        "What is 100/5?",
        "Which is bigger: 0.5 or 0.05?",
        "What is 9*9?",
        "Which is bigger: -5 or 5?",
        "What is 25*4?",
        "Which is bigger: 100 or 99?",
    ],
    "personal": [
        "У тебя есть чувства?",
        "Ты живой?",
        "Ты человек?",
        "Ты бот?",
        "Ты искусственный интеллект?",
        "Тебе нравится общаться?",
        "Ты устаёшь?",
        "Что ты любишь?",
        "Что тебя радует?",
        "Что тебя расстраивает?",
        "Do you have feelings?",
        "Are you alive?",
        "Are you human?",
        "Are you a bot?",
        "Are you an artificial intelligence?",
        "Do you like to chat?",
        "Do you get tired?",
        "What do you like?",
        "What makes you happy?",
        "What makes you sad?",
    ],
}


def main():
    total = 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open('w', encoding='utf-8') as f:
        for cat, prompts in PROMPTS.items():
            for p in prompts:
                f.write(json.dumps({"category": cat, "prompt": p}, ensure_ascii=False) + '\n')
                total += 1
    print(f"✅ Создано {total} промптов в {OUTPUT}")
    print(f"Категории: {[(c, len(p)) for c, p in PROMPTS.items()]}")


if __name__ == '__main__':
    main()
