"""Генерирует статический dashboard (HTML) для GitHub Pages."""
import sys
import json
from pathlib import Path
from datetime import datetime

sys.path.insert(0, ".")


def make_html(history, perplexities, samples, latest_ckpt):
    """Генерирует HTML дашборд."""
    final = history[-1] if history else {}
    final_loss = final.get("loss", "N/A")
    final_step = final.get("step", "N/A")

    # Loss curve points
    losses = [h.get("loss") for h in history if "loss" in h]
    loss_points = "[" + ",".join(f"[{i},{l}]" for i, l in enumerate(losses) if l) + "]"

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>LLM Training Dashboard</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<style>
  body {{ font-family: monospace; max-width: 1200px; margin: 0 auto; padding: 20px; background: #0d1117; color: #c9d1d9; }}
  h1, h2 {{ color: #58a6ff; }}
  .stats {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }}
  .stat {{ background: #161b22; padding: 20px; border-radius: 8px; border: 1px solid #30363d; }}
  .stat-value {{ font-size: 2em; font-weight: bold; color: #f0883e; }}
  .stat-label {{ color: #8b949e; font-size: 0.9em; }}
  table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
  th, td {{ padding: 8px; text-align: left; border-bottom: 1px solid #30363d; }}
  th {{ background: #161b22; color: #58a6ff; }}
  .sample {{ background: #161b22; padding: 10px; margin: 5px 0; border-left: 3px solid #58a6ff; font-size: 0.9em; }}
  .footer {{ margin-top: 40px; color: #8b949e; text-align: center; font-size: 0.9em; }}
</style>
</head>
<body>
<h1>🚀 LLM Training Dashboard</h1>
<p>1B parameter model, trained on FineWeb-Edu, custom framework</p>

<div class="stats">
  <div class="stat">
    <div class="stat-label">Current Step</div>
    <div class="stat-value">{final_step}</div>
  </div>
  <div class="stat">
    <div class="stat-label">Current Loss</div>
    <div class="stat-value">{final_loss if isinstance(final_loss, str) else f"{final_loss:.4f}"}</div>
  </div>
  <div class="stat">
    <div class="stat-label">Latest Checkpoint</div>
    <div class="stat-value" style="font-size: 1em;">{latest_ckpt or 'N/A'}</div>
  </div>
  <div class="stat">
    <div class="stat-label">Last Updated</div>
    <div class="stat-value" style="font-size: 1em;">{datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
  </div>
</div>

<h2>📉 Training Loss</h2>
<canvas id="lossChart" width="400" height="150"></canvas>
<script>
const ctx = document.getElementById('lossChart').getContext('2d');
new Chart(ctx, {{
  type: 'line',
  data: {{
    labels: Array.from({{length: {len(losses)}}}, (_, i) => i),
    datasets: [{{
      label: 'Train Loss',
      data: {loss_points},
      borderColor: '#f0883e',
      backgroundColor: 'rgba(240, 136, 62, 0.1)',
      fill: true,
      tension: 0.3,
    }}]
  }},
  options: {{
    plugins: {{ legend: {{ labels: {{ color: '#c9d1d9' }} }} }},
    scales: {{
      x: {{ ticks: {{ color: '#8b949e' }}, grid: {{ color: '#30363d' }} }},
      y: {{ ticks: {{ color: '#8b949e' }}, grid: {{ color: '#30363d' }} }}
    }}
  }}
}});
</script>

<h2>📊 Perplexity on Different Datasets</h2>
<table>
  <tr><th>Dataset</th><th>PPL</th></tr>
"""

    for name, ppl in (perplexities or {}).items():
        html += f"  <tr><td>{name}</td><td>{ppl if ppl else 'N/A'}</td></tr>\n"

    html += "</table>\n"

    html += "<h2>🎯 Latest Generations</h2>\n"
    if samples:
        for s in samples[-5:]:
            html += f'<div class="sample"><b>{s.get("prompt", "")[:50]}</b><br>{s.get("generation", "")[:200]}</div>\n'

    html += """
<div class="footer">
  <p>LLM-from-scratch-1b · Generated by training_report.py · Auto-updated by GitHub Actions</p>
</div>
</body>
</html>
"""
    return html


def main():
    log_path = Path("checkpoints/v1_fineweb/train_log.jsonl")
    if not log_path.exists():
        for p in sorted(Path("checkpoints").rglob("train_log.jsonl"), reverse=True):
            log_path = p
            break

    history = []
    if log_path.exists():
        for line in log_path.read_text(encoding="utf-8").strip().split("\n"):
            try:
                history.append(json.loads(line))
            except Exception:
                pass

    # Load perplexities
    perplexities = {}
    eval_path = Path("logs/eval_benchmark.jsonl")
    if eval_path.exists():
        lines = eval_path.read_text().strip().split("\n")
        if lines:
            try:
                last = json.loads(lines[-1])
                perplexities = last.get("perplexities", {})
            except Exception:
                pass

    # Load samples
    samples = []
    sample_path = Path("logs/sample_history.jsonl")
    if sample_path.exists():
        lines = sample_path.read_text().strip().split("\n")
        for line in lines[-3:]:
            try:
                row = json.loads(line)
                samples.extend(row.get("samples", []))
            except Exception:
                pass

    # Latest checkpoint
    latest_ckpt = None
    if log_path.parent.exists():
        ckpts = sorted(log_path.parent.glob("step*.pt"), reverse=True)
        if ckpts:
            latest_ckpt = ckpts[0].name

    html = make_html(history, perplexities, samples, latest_ckpt)
    out_path = Path("docs/index.html")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    print(f"Dashboard saved to {out_path}")


if __name__ == "__main__":
    main()
